simbot:
  # 是否在bot注册完成后自动启动他们。
  # 默认为 true
  auto-start-bots: true
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qrot?useSSL=false&charset=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    druid:
      max-active: 8 # 最大活跃数量 默认8
      min-idle: 1 # 最小空闲数 默认0
      initial-size: 3 # 初始连接数
      max-wait: 2000 # 获取连接最大等待时间 默认 -1
      validation-query: select 1
      validation-query-timeout: 5000
      time-between-eviction-runs-millis: 2000 # 间隔多久进行检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 600000 # 配置连接在池中最小生存的时间
      max-wait-thread-count: 20 # 最大等待线程数
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: qxxzbdx@163.com
    password: GBRAEGYBAQZDHYKZ
email:
  #系统发件人邮箱
  system: qxxzbdx@163.com
  hr: 2578908933@qq.com
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.stuxx.model.entity

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    ### xxl-job, access token
    accessToken: Xiao010422
    executor:
      ip: 127.0.0.1
      address: http://127.0.0.1:9999
      ### xxl-job executor appname
      appname: qrot
      port: 9999
      logpath: logs/qrot/jobhandler
      logretentiondays: 30

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 5
      keepAliveSeconds: 36000
      queue_capacity: 50
      name:
        prefix: timing-job-service-